application:
  # Set to true if testing production env without Apache/Nginx
  serve_static_assets: false
  # Set to "https://" if running behind Apache/Nginx + https
  protocol: "http://"
  fake_cas: false
  fake_cas_id: "1" # Change this to the UID you want to fake cas auth with.
  # WebMock is not thread-safe, and so fake proxy support should
  # be disabled when no fakes are needed (e.g., in production).
  fake_proxies_enabled: true
  # timeout (in seconds) for outgoing http request establishment
  outgoing_http_timeout: 30
  layer: development
  # Lifespan of session cookie
  session_expiration: <%= 4.hours %>

logger:
  level: <%= ENV['LOGGER_LEVEL'] || WARN %>
  stdout: <%= ENV['LOGGER_STDOUT'] %>
  slow_query_threshold_in_ms: 700
  slow_request_threshold_in_ms:
    default: 30000
    /api/my/status: 10000
  proxy_threshold_in_ms: 8000

cas_server: 'https://auth.berkeley.edu/cas'

cas_logout_url: 'https://auth.berkeley.edu/cas/logout'

# Database settings
postgres:
  database: <%= ENV['DB_ENV_POSTGRESQL_DB'] || 'calcentral_production' %>
  username: <%= ENV['DB_ENV_POSTGRESQL_USER'] || 'calcentral_production' %>
  password: <%= ENV['DB_ENV_POSTGRESQL_PASS'] || 'secret' %>
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] || 'localhost' %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] || '5432' %>
  pool: 95

edodb:
  fake: false
  adapter:
  driver:
  url:
  username:
  password:
  pool: 95

campusdb:
  fake: false
  adapter: h2
  driver: org.h2.Driver
  url: jdbc:h2:mem:h2CampusOracle::CampusDataSource;DB_CLOSE_DELAY=-1;MODE=Oracle
  username: sa
  password: sa
  pool: 95
  fake_user_id: "300939"

terms:
  # Limit how far back our academic history goes.
  oldest: spring-2010
  # This term and earlier will pull academic data from legacy CampusOracle. Later terms will pull from EdoOracle.
  legacy_cutoff: summer-2016
  # Timestamp in UTC, needed when testing against test Campus data.
  # Can also be used to force selection of a "current term" different
  # from the default.
  fake_now:

test_sqlite:
  pool: 3

# Proxy support
# MUST BE SET FOR DEVELOPMENT & PRODUCTION
# Example generated with SecureRandom.base64(32)
oauth2:
  key: "IeGpe9iq27Glqujd8pGH1+xM8C/ofm97Lp74N+6cN0I="
  encryption: "aes-256-cbc"

# Proxy settings
# Set "fake: true" for any inaccessible ones
canvas_proxy:
  admin_access_token: "someMumboJumbo"
  # URL for Canvas server
  url_root: "http://localhost:12345"
  fake: false
  account_id: '90242'
  admin_tools_account_id: '129607'
  official_courses_account_id: '129410'
  projects_account_id: '129407'
  projects_term_id: '5494'
  default_grading_scheme_id: '4068930'
  export_directory: 'tmp/canvas'
  lti_key: 'someMumboJumbo'
  lti_secret: 'someMumboJumbo'
  # Only used for testing + recording responses
  test_user_id: "300846"
  test_user_access_token: "someMumboJumbo"
  mixed_sis_user_id: true
  # Set to any string to make integration scripts create CSV files and log intended updates
  # without actually changing anything in Canvas.
  dry_run_import: <%= ENV['CANVAS_DRY_RUN_IMPORT'] || '' %>
  # Set to false to disable synchronization of obfuscated names in Dev/QA.
  maintain_user_names: true
  # Set to false to disable user account inactivation based on campus data.
  inactivate_expired_users: true
  # Set to false if Canvas permissions block our ability to delete an invalid email address.
  delete_bad_emails: true
  # URL for scripts to point to CalCentral/Junction
  app_provider_host: 'http://localhost:3000'
  test_admin_id:
  test_servers:
  test_cas_url: 'https://auth-test.berkeley.edu/cas'
  # If reports are provided through Google Drive, this is the UID that creates them.
  reporter_uid:

ldap:
  host: 'nds.berkeley.edu'
  port: 636
  application_bind: 'uid=someApp,ou=applications,dc=berkeley,dc=edu'
  application_password: 'someMumboJumbo'

google_proxy:
  client_id: 1
  client_secret: 'bogusClientSecret'
  scope: 'profile email https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/tasks https://www.googleapis.com/auth/drive.readonly.metadata https://mail.google.com/mail/feed/atom/'
  fake: false
  #Maps to tammi.chang.clc@gmail.com. Used for testing + recording responses
  test_user_access_token: "bogusAccessToken"
  test_user_refresh_token: "bogusRefreshToken"
  atom_mail_feed_url: "https://mail.google.com/mail/feed/atom/"

cal_link_proxy:
  fake: false
  base_url: "https://callink.berkeley.edu"
  public_key: secret set in production
  private_key: secret set in production

bearfacts_proxy:
  fake: false
  app_id: ''
  app_key: ''
  base_url: "https://apis-dev.berkeley.edu/bearfacts-apis"

cal_groups_proxy:
  fake: false
  username: 'secret'
  password: 'secret'
  base_url: 'https://group-test.berkeley.edu/gws/servicesRest/json/v2_2_100'

calmail_proxy:
  fake: false
  api_key: '99999'
  base_url: 'https://example.com/manage/api1'
  domain: 'bcourses-lists.berkeley.edu'
  owner_address: 'owner@example.com'
  owner_uid: '211159'

eft_proxy:
  fake: true
  # QA Environment
  base_url: 'https://eftstudent-qa.berkeley.edu/api/'
  token: 'secret'

regstatus_proxy:
  fake: false
  app_id: ''
  app_key: ''
  base_url: 'https://apis.berkeley.edu/cxf/asws/regstatus'

myfinaid_proxy:
  fake: false
  app_id: ''
  app_key: ''
  base_url: "https://apis-qa.berkeley.edu/myfinaid"

financials_proxy:
  fake: false
  base_url: "https://integration-qa.berkeley.edu/cfv"
  username: ''
  password: ''

hub_term_proxy:
  fake: false
  app_id: ''
  app_key: ''
  base_url: 'https://apis.berkeley.edu/uat/sis/v1/terms'

textbooks_proxy:
  fake: false
  base_url: "https://calstudentstore.berkeley.edu"
  token: secret set per deployment layer

webcast_proxy:
  fake: false
  base_url: 'https://webcast-cc-staging.ets.berkeley.edu'
  username: ''
  password: ''

audio_proxy:
  base_url: 'https://wbe-itunes.berkeley.edu'

blog_latest_release_notes_feed_proxy:
  fake: false
  base_url: "https://www.ets.berkeley.edu/news-archive/calcentral-release-notes/feed"

cal1card_proxy:
  fake: false
  base_url: 'https://webstage.housing.berkeley.edu/c1c/dyn'
  username: 'secret'
  password: 'secret'

# Analytics settings ID
# This will need to be different for every server (dev/qa/production)
google_analytics_id: UA-XXXXXX-X

# Sentry URL
# We use https://getsentry.com for our JavaScript Error logging
sentry_url: "https://facf7ad7bd7047f0a356e9322107ce50@app.getsentry.com/7185"

# Cache settings. 0 means never expire.
# WARNING: memcached's upper limit is 30 days. Specifying longer expiration than that will
# result in entries expiring instantly.
cache:
  # Array of server addresses in cluster (for memcached). These must match the hostnames
  # of the application cluster for CalCentral's BackgroundJobsCheck to work correctly.
  servers: ["localhost"]
  maximum_expires_in: <%= 29.days %>
  race_condition_ttl: <%= 10.seconds %>
  stale_connection_flush_interval: <%= 30.seconds %>
  store: "memcached"
  log_level: <%= Logger::WARN %>
  expiration:
    default: <%= 35.minutes %>
    failure: <%= 30.seconds %>
    Cache::FeedUpdateWhiteboard: <%= 5.minutes %>
    LiveUpdatesWarmer: <%= 2.minutes %>
    BackgroundJobsCheck: <%= 29.days %>
    MyAcademics::Merged: NEXT_08_00
    MyActivities::Merged: <%= 8.hours %>
    MyBadges::Merged: NEXT_00_00
    MyCampusLinksController: NEXT_08_00
    MyClasses::Merged: NEXT_08_00
    MyGroups::Merged: NEXT_08_00
    MyTasks::Merged: <%= 10.minutes %>
    UpNext::MyUpNext: NEXT_00_00
    User::Api: NEXT_08_00
    User::AuthenticationValidator: <%= 8.hours %>
    User::AuthenticationValidator::short: <%= 5.minutes %>
    UserApiController: <%= 4.hours %>
    Cal1card::Photo: <%= 4.hours %>

    Canvas::CourseStudents: <%= 15.minutes %>
    Canvas::CourseTeachers: <%= 5.minutes %>
    CanvasBackgroundJobs: <%= 24.hours %>
    CanvasLti::Egrades: <%= 1.minute %>
    CanvasLti::Lti: <%= 5.minutes %>
    Advising::MyAdvising: <%= 2.hours %>

    MyAcademics::CollegeAndLevel: NEXT_08_00
    MyAcademics::GpaUnits: NEXT_08_00

    Berkeley::Terms: NEXT_08_00
    Finaid::TimeRange: <%= 4.hours %>

    CampusOracle::CourseSections: NEXT_08_00
    CampusOracle::UserAttributes: NEXT_08_00

    Canvas::MergedUserSites: <%= 30.minutes %>
    Canvas::UserCourses: <%= 30.minutes %>
    Canvas::Groups: <%= 30.minutes %>
    Canvas::UserActivityStream: <%= 10.minutes %>
    Canvas::Terms: <%= 8.hours %>
    Canvas::Todo: <%= 20.minutes %>
    Canvas::UpcomingEvents: <%= 20.minutes %>

    MyBadges::GoogleCalendar: <%= 4.minutes %>
    MyBadges::GoogleDrive: <%= 10.minutes %>
    MyBadges::GoogleMail: <%= 4.minutes %>

    MyTasks::GoogleTasks: <%= 4.minutes %>

    CalLink::Memberships: <%= 4.hours %>
    CalLink::Organization: <%= 4.hours %>

    Textbooks::Proxy: <%= 24.hours %>

    ServiceAlerts::Merged: <%= 24.hours %>

    CampusSolutions::AddressLabel: <%= 29.days %>
    CampusSolutions::AddressType: <%= 29.days %>
    CampusSolutions::Country: <%= 29.days %>
    CampusSolutions::CurrencyCode: <%= 29.days %>
    CampusSolutions::DelegateManagementURL: <%= 24.hours %>
    CampusSolutions::DelegateStudents: <%= 24.hours %>
    CampusSolutions::DelegateTermsAndConditions: <%= 24.hours %>
    CampusSolutions::EthnicitySetup: <%= 29.days %>
    CampusSolutions::FerpaDeeplink: <%= 24.hours %>
    CampusSolutions::LanguageCode: <%= 29.days %>
    CampusSolutions::Link: <%= 24.hours %>
    CampusSolutions::MyChecklist: <%= 15.minutes %>
    CampusSolutions::MyDeposit: <%= 2.minutes %>
    CampusSolutions::MyHigherOneUrl: <%= 1.seconds %>
    CampusSolutions::NameType: <%= 29.days %>
    CampusSolutions::SirConfig: <%= 24.hours %>
    CampusSolutions::State: <%= 29.days %>
    CampusSolutions::SlrDeeplink: <%= 24.hours %>
    CampusSolutions::Translate: <%= 24.hours %>
    CampusSolutions::DashboardUrl: <%= 29.days %>

    CalnetCrosswalk::ByUid: <%= 4.hours %>
    CalnetCrosswalk::BySid: <%= 4.hours %>

    HubEdos::MyStudent: <%= 20.minutes %>

# Cache warmer settings
cache_warmer:
  # Number to decrement db pool to limit the number of warmer threads
  fudge_factor: 1

# Bearfacts JMS event queue
ist_jms:
  fake: true
  enabled: true
  freshen_recording: false
  connections:
    - url: 'tcp://localhost:61616'
      queues: [ 'testqueue' ]
      #  username: USERNAME
      #  password: PASSWORD

# This will enable http basic auth for the app and should NEVER be enabled in production
developer_auth:
  enabled: false
  password: topsecret!

hot_plate:
  last_visit_cutoff: <%= 10.days %>
  enabled: true

background_jobs_check:
  time_between_pings: <%= 5.minutes %>

youtube_splash_id: '3Iz1NT9QKjI'

oec:
  administrator_uid: ''
  local_write_directory: 'tmp/oec'
  explorance:
    sftp_server: ''
    sftp_port: 22
    sftp_user: ''
    ssh_private_key_file: ''
  google:
    uid: ''
    client_id: 'oecClientId'
    client_secret: 'oecClientSecret'
    access_token: 'oecAccessToken'
    refresh_token: 'oecRefreshToken'
    scope: 'profile email https://mail.google.com/mail/feed/atom/ https://spreadsheets.google.com/feeds/ https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/drive.apps.readonly https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/drive.readonly.metadata https://www.googleapis.com/auth/tasks'
  current_terms_codes: [{
    year: 2015,
    code: "C"
  }]
  departments: [ 'A,RESEC', 'BIOLOGY', 'CATALAN', 'CHEM', 'DATASCI', 'ECON', 'ENE,RES', 'ENVECON', 'EPS', 'ESPM', 'GWS', 'INFO', 'INTEGBI', 'LGBT', 'LINGUIS', 'MATH', 'MCELLBI', 'NUSCTX', 'PHYSICS', 'PLANTBI', 'POL SCI', 'PORTUG', 'PSYCH', 'SPANISH', 'STAT' ]

class_calendar:
  slice_size: 10000
  slice_pause_duration: 600
  access_token: secret
  refresh_token: secret
  departments: [ 'BIOLOGY', 'CHEM' ]

ui_selenium:
  base_url: https://calcentral-dev.berkeley.edu
  cal_net_url: https://auth-test.berkeley.edu
  canvas_base_url: https://ucberkeley.beta.instructure.com
  canvas_qa_sub_account: secret
  google_auth_url: /api/google/request_authorization?force_domain=false
  layer: development

  # Alternative browsers for Selenium tests: chrome, safari, ie
  web_driver: firefox

  google_task_timeout: 12
  page_event_timeout: 10
  page_load_timeout: 20
  campus_solutions_timeout: 6
  live_update_timeout_delta: 180
  academics_timeout: 20
  canvas_update_timeout: 60
  canvas_username: secret
  canvas_password: secret
  canvas_id: secret
  test_user_password: secret
  oski_username: secret
  oski_password: secret
  oski_gmail_username: secret
  oski_gmail_password: secret
  ets_qa_ldap_username: secret
  ets_qa_ldap_password: secret
  ets_qa_gmail_username: secret
  ets_qa_gmail_password: secret
  admin_uid: secret

advising_proxy:
  fake: false
  base_url: 'https://bhive.berkeley.edu/api'
  username: secret
  password: secret

campus_solutions_proxy:
  fake: true
  base_url: 'https://bcs-web-dev-03.is.berkeley.edu:8443/PSIGW/RESTListeningConnector/PSFT_CS'
  logout_url: 'https://bcs-web-dev-03.is.berkeley.edu:8443/psp/logout/EMPLOYEE/HRMS/?cmd=logout'
  username: secret
  password: secret
  http_timeout_seconds: 30

hub_edos_proxy:
  fake: true
  base_url: 'https://sis-integration.berkeley.edu/apis/sis/v1/students'
  username: secret
  password: secret
  http_timeout_seconds: 30

calnet_crosswalk_proxy:
  fake: true
  base_url: 'https://registry-d1.calnet.1918.berkeley.edu:8453/registry-service/api/v1/identifiers'
  username: secret
  password: secret
  http_timeout_seconds: 30

campus_solutions_links:
  advising:
    multi_year_academic_planner_generic: ''
    multi_year_academic_planner: ''
    schedule_planner: ''
    web_now_documents: ''
    eforms_center: ''
    eforms_work_list: ''
  academics:
    enrollment_verification_google: ''
    enrollment_Verification: ''

# A feature will be disabled if the corresponding feature-flag is false or nil.
features:
  advising: false
  audio: false
  authentication_validator: false
  background_jobs_check: true
  cal1card: false
  class_enrollment_summer_2016: false
  class_info_enrollment_tab: false
  course_manage_official_sections: false
  cs_academic_planner: false
  cs_academic_profile_prefers_legacy: true
  cs_academic_progress_report: false
  cs_advising_scheduler_view: false
  cs_advisor_student_lookup: false
  cs_billing: false
  cs_delegated_access: false
  cs_enrollment_card: false
  cs_fin_aid: false
  cs_fin_aid_award_compare: false
  cs_holds: false
  cs_logout: false
  cs_profile: true
  cs_profile_emergency_contacts: false
  cs_profile_languages: false
  cs_profile_visible_for_legacy_users: true
  cs_profile_work_experience: false
  cs_sir: true
  cs_transfer_credit: false
  hub_term_api: true
  enrollment_verification: false
  legacy_regblocks: true
  manage_site_mailing_lists: false
  my_fin_aid: false
  prevent_acting_as_users_from_posting: true
  reauthentication: true
  regstatus: true
  textbooks: false
  videos: false
  webcast_sign_up_on_calcentral: false
